# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            JohnTGZ
tagline:          'A Jekyll theme'
description:      'A Personal Blog where I ramble about and dabble in robotics and philosophical nonsense.'
url:              http://johntgz.github.io
baseurl:          /

author:
  name:           'John Tan'
  url:            https://github.com/JohnTGZ

paginate:         5

# Custom vars
version:          2.1.0

mysites:
  github: https://github.com/JohnTGZ
  linkedin: https://www.linkedin.com/in/john-tan-guan-zhong-681815156

github:     
  plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet


excerpt_separator: "<!-- excerpt-end -->"
