# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            JohnTGZ
tagline:          'A Jekyll theme'
description:      'A Personal Blog where I ramble about robotics and life.'
url:              http://johntgz.github.io
baseurl:          /

author:
  name:           'John Tan'
  url:            https://github.com/JohnTGZ

paginate:         5

github:     
  plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

# Custom vars

mysites:
  github: https://github.com/JohnTGZ
  linkedin: https://www.linkedin.com/in/john-tan-guan-zhong-681815156



excerpt_separator: "<!-- excerpt-end -->"
