# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            JohnTGZ
tagline:          'Byte, Sweat and Cheers'
description:      'Join me in navigating the obscure landscape of robotics and computing.'
url:              http://johntgz.github.io
baseurl:          /

author:
  name:           'John Tan'
  url:            https://github.com/JohnTGZ

paginate:         5

github:     
  plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

# Custom vars

mysites:
  github: https://github.com/JohnTGZ
  linkedin: https://www.linkedin.com/in/john-tan-guan-zhong-681815156


excerpt_separator: "<!-- excerpt-end -->"
